openapi: 3.1.0
info:
  title: Kurs-API
  version: 1.0.0
servers:
  - url: https://kurs-api.onrender.com
paths:
  /price:
    get:
      operationId: get_price
      summary: Kurs in EUR oder gewünschter Währung abrufen
      parameters:
        - in: query
          name: symbol
          required: true
          schema:
            type: string
          description: Börsensymbol (z. B. AAPL, BTCUSD)
        - in: query
          name: currency
          required: false
          schema:
            type: string
            default: EUR
          description: Zielwährung (z. B. EUR, USD, CHF)
      responses:
        '200':
          description: Kursantwort
          content:
            application/json:
              schema:
                type: object
                properties:
                  symbol:
                    type: string
                  price:
                    type: number
                  currency:
                    type: string
  /fundamentals:
    get:
      operationId: get_fundamentals
      summary: Finanzkennzahlen eines Unternehmens für ein bestimmtes Jahr
      parameters:
        - in: query
          name: symbol
          required: true
          schema:
            type: string
          description: Börsensymbol, z. B. AAPL
        - in: query
          name: year
          required: true
          schema:
            type: integer
          description: Jahr, z. B. 2023
      responses:
        '200':
          description: Fundamentaldaten als JSON
          content:
            application/json:
              schema:
                type: object
                properties:
                  revenue:
                    type: number
                  ebit:
                    type: number
                  net_income:
                    type: number
                  free_cash_flow:
                    type: number
                  net_margin:
                    type: number

  paths:
  /analyze:
    get:
      operationId: analyzeStock
      summary: Buffett/Munger Analyse mit DCF und Margin of Safety
      description: Führt eine Fundamentalanalyse inkl. DCF und Margin of Safety für das angegebene Symbol durch und speichert das Ergebnis automatisch.
      parameters:
        - name: symbol
          in: query
          required: true
          description: Das Börsensymbol (z. B. AAPL, NVO)
          schema:
            type: string
        - name: currency
          in: query
          required: false
          description: Zielwährung (z. B. EUR)
          schema:
            type: string
            default: EUR
      responses:
        '200':
          description: Analyse erfolgreich durchgeführt
          content:
            application/json:
              schema:
                type: object
                properties:
                  symbol:
                    type: string
                  price:
                    type: number
                  fair_value:
                    type: number
                  mos_price:
                    type: number
                  free_cash_flow:
                    type: number
                    nullable: true
                  net_income:
                    type: number
                    nullable: true
                  revenue:
                    type: number
                    nullable: true
                  verdict:
                    type: string
                  file_saved:
                    type: string
        '400':
          description: Ungültige Anfrage
        '500':
          description: Serverfehler


